<style type="text/css" media="all">
th{font-weight:bold;}
</style>
<h1>BPCO: Che cos&rsquo;&egrave;?</h1>
<p><br />
  <strong>BPCO</strong> sta per <strong>B</strong>ronco<strong>P</strong>neumopatia <strong>C</strong>ronica <strong>O</strong>struttiva, termine utilizzato per indicare due malattie molto diffuse, chiamate finora <strong>bronchite cronica</strong> ed <strong>enfisema polmonare</strong>, che spesso coesistono nello stesso paziente. Le linee guida internazionali forniscono la seguente definizione:<strong> </strong></p>
<p><em>&rdquo;Una malattia&nbsp;prevenibile&nbsp;e curabile, caratterizzata da&nbsp;limitazione persistente del flusso aereo&nbsp;che&nbsp;&egrave; generalmente progressiva ed&nbsp;associata ad una maggiore&nbsp;risposta&nbsp;infiammatoria cronica&nbsp;delle vie aeree e&nbsp;del polmone&nbsp;a particelle nocive&nbsp;o gas</em> <em>(nella maggior parte dei casi il fumo di sigarette)&rdquo;.</em></p>
<p>In definitiva, si tratta di una <strong>malattia progressiva </strong>che causa un <strong>deterioramento della funzionalit&agrave; respiratoria</strong>, attraverso un&rsquo;<strong>ostruzione irreversibile delle vie aeree </strong>e un danneggiamento <strong>di aree polmonari</strong>. Si manifesta clinicamente con <strong>tosse e catarro cronici</strong> e <strong>progressiva mancanza di respiro</strong>.</p>
<p><strong>Che cosa significa questo per il paziente?</strong> <br />
  La BPCO &egrave; causa di disturbi respiratori come la <strong>tosse</strong>, spesso con catarro, la <strong>mancanza di respiro</strong> e <strong>frequenti bronchiti</strong> che si manifestano con l&rsquo;aggravarsi di queste manifestazioni. Tali problemi provocano una graduale riduzione della capacit&agrave; di svolgere le attivit&agrave; quotidiane in casa e al lavoro. Quando la BPCO si aggrava possono comparire anche i segni dell&rsquo;insufficienza respiratoria e cio&egrave; della carenza di ossigeno e dell&rsquo;accumulo di anidride carbonica.</p>
<p><strong>Come si misura l&rsquo;ostruzione del flusso aereo?</strong><strong> </strong><br />
  Attraverso un esame semplice, rapido, indolore e sicuro che si chiama <strong>spirometria</strong>. La spirometria &egrave; l&rsquo;esame di base per misurare la nostra funzionalit&agrave; respiratoria ed &egrave; spesso alterata nel paziente con BPCO anche prima della comparsa di sintomi importanti per cui &egrave; essenziale che sia eseguita nei soggetti a rischio anche in assenza di sintomi come misura di salute generale.</p>
<p><strong>Come si cura la BPCO?</strong> <br />
  Sulla base delle evidenze pi&ugrave; recenti, il medico raccomanda l&rsquo;uso regolare dei <strong>broncodilatatori a lunga durata d&rsquo;azione</strong> dalla fase moderata alla fase grave, di tipo agonista-adrenergico come salmeterolo e formoterolo e anticolinergico come il tiotropio, piuttosto che i <strong>broncodilatatori a rapida durata d&rsquo;azione</strong>. Inoltre &egrave; indicato l&rsquo;uso di <strong>cortisonici</strong> <strong>per via inalatoria</strong> in genere per i pazienti con frequenti riacutizzazioni. L&rsquo;associazione di cortisonici e broncodilatatori a lunga durata d&rsquo;azione in un unico inalatore &egrave; risultata pi&ugrave; efficace della somministrazione attraverso due erogatori separati. Nelle riacutizzazioni si deve intervenire precocemente con il trattamento adeguato iniziando a base di <strong>cortisone orale</strong> e talvolta di <strong>antibiotici</strong>.<br />
  Oltre al trattamento farmacologico &egrave; importante la <strong>riabilitazione</strong>, un fondamento della quale &egrave; l&rsquo;<strong>esercizio fisico</strong>, la <strong>terapia nutrizionale</strong> e <strong>l&rsquo;ossigenoterapia</strong> domiciliare.</p>
